const { prisma } = require("./client");

const course = [
    { name: "Bachelor of Science in Computer Science" },
    { name: "Bachelor of Science in Information Technology" },
    { name: "Bachelor of Science in Civil Engineering" },
    { name: "Bachelor of Science in Computer Engineering" },
    { name: "Bachelor of Science in Electrical Engineering" },
    { name: "Bachelor of Science in Electronic Engineering" },
    { name: "Bachelor of Science in Mechanical Engineering" },
    { name: "Bachelor of Early Childhood Education" },
    { name: "Bachelor of Elementary Education" },
    { name: "Bachelor of Elementary Education Major in Early Childhood Education" },
    { name: "Bachelor of Elementary Education Major in General Education" },
    { name: "Bachelor of Elementary Education Major in Special Education" },
    { name: "Bachelor of Secondary Education Major in English" },
    { name: "Bachelor of Secondary Education Major in Filipino" },
    { name: "Bachelor of Secondary Education Major in Mathematics" },
    { name: "Bachelor of Secondary Education Major in Science" },
    { name: "Bachelor of Special Needs Education: Generalist" },
    { name: "Bachelor of Science in Accountancy" },
    { name: "Bachelor of Science in Business Administration Major in Financial Management" },
    { name: "Bachelor of Science in Business Administration Major in Management Accounting" },
    { name: "Bachelor of Science in Business Administration Major in Marketing Management" },
    { name: "Bachelor of Science in Tourism Management" },
    { name: "Bachelor of Arts in Mass Communication" },
    { name: "Bachelor of Science in Hospitality Management" },
    { name: "Bachelor of Science in Psychology" },
    { name: "Bachelor of Science in Nursing" },
    { name: "Bachelor of Science in Criminology" },
    { name: "Doctor of Philosophy Educational Leadership and Management" },
    { name: "Master in Education Major in Educational Leadership" },
    { name: "Master in Education Major in English Language Teaching" },
    { name: "Master in Information Technology" },
    { name: "Master of Arts in Education Major in Educational Management" },
];

const skills = [
  { name: "Programming" },
  { name: "Web Development" },
  { name: "Database Management" },
  { name: "Networking" },
  { name: "Cybersecurity" },
  { name: "Cloud Computing" },
  { name: "Data Science" },
  { name: "Software Testing and Quality Assurance" },
  { name: "Mobile App Development" },
  { name: "IT Support and Helpdesk Management" },
  { name: "Patient Assessment and Care Planning" },
  { name: "Medication Administration" },
  { name: "Wound Care Management" },
  { name: "Clinical Documentation" },
  { name: "Critical Thinking and Problem Solving" },
  { name: "Health Promotion and Disease Prevention" },
  { name: "Infection Control Procedures" },
  { name: "Patient Education and Counseling" },
  { name: "Emergency Response and CPR" },
  { name: "Ethics and Professionalism in Nursing" },
  { name: "Criminal Law and Procedure" },
  { name: "Forensic Science Techniques" },
  { name: "Crime Scene Investigation" },
  { name: "Criminal Psychology" },
  { name: "Victimology and Victim Assistance" },
  { name: "Juvenile Justice Systems" },
  { name: "Policing Strategies and Community Policing" },
  { name: "Criminal Justice Ethics" },
  { name: "Risk Assessment and Management" },
  { name: "Crime Prevention Strategies" },
  { name: "Mechanical Engineering Design" },
  { name: "Electrical Circuit Analysis" },
  { name: "Structural Analysis and Design" },
  { name: "Thermodynamics and Fluid Mechanics" },
  { name: "Engineering Mathematics" },
  { name: "CAD/CAM Software Proficiency" },
  { name: "Project Management in Engineering" },
  { name: "Materials Science and Engineering" },
  { name: "Environmental Engineering Principles" },
  { name: "Robotics and Automation" },
  { name: "Architectural Design Principles" },
  { name: "Building Information Modeling" },
  { name: "Construction Documents and Specifications" },
  { name: "Urban Planning and Design" },
  { name: "Sustainable Architecture" },
  { name: "Interior Design Concepts" },
  { name: "Historical Preservation and Restoration" },
  { name: "Architectural Visualization Techniques" },
  { name: "Building Codes and Regulations" },
  { name: "Site Analysis and Planning" },
  { name: "Ballet Technique and Performance" },
  { name: "Contemporary Dance Styles" },
  { name: "Jazz Dance Techniques" },
  { name: "Hip Hop and Street Dance" },
  { name: "Partner and Group Choreography" },
  { name: "Dance History and Appreciation" },
  { name: "Improvisation" },
  { name: "Physical Conditioning for Dancers" },
  { name: "Stage Presence and Performance" },
  { name: "Dance Production and Event Management" },
  { name: "Drawing and Sketching Techniques" },
  { name: "Painting with Various Media" },
  { name: "Sculpture and 3D Art Forms" },
  { name: "Printmaking Techniques" },
  { name: "Mixed Media Artistry" },
  { name: "Art History and Criticism" },
  { name: "Color Theory and Composition" },
  { name: "Digital Art and Graphic Design" },
  { name: "Art Exhibition Curation and Management" },
  { name: "Art Education and Community Outreach" },
  { name: "Music Business and Marketing" },
  { name: "Live Sound Engineering and Mixing" },
  { name: "Music Education and Pedagogy" },
  { name: "Stage Performance and Presence" },
  { name: "Music Technology and Digital Instruments" },
  { name: "Business Management and Leadership" },
  { name: "Financial Analysis and Reporting" },
  { name: "Marketing Strategy and Brand Management" },
  { name: "Entrepreneurship and Business Development" },
  { name: "Project Management" },
  { name: "Supply Chain Management" },
  { name: "Business Ethics and Corporate Social Responsibility" },
  { name: "Market Research and Analysis" },
  { name: "Human Resource Management" },
  { name: "Business Communication and Negotiation" },
  { name: "Public Speaking and Presentation" },
  { name: "Written Communication" },
  { name: "Interpersonal Communication" },
  { name: "Media Production" },
  { name: "Social Media Management" },
  { name: "Cross-Cultural Communication" },
  { name: "Conflict Resolution and Mediation" },
  { name: "Journalism and News Reporting" },
  { name: "Editing and Proofreading" },
  { name: "Technical Writing and Documentation" }
]


async function Seed(){
    await prisma.skill.createMany({
        data: skills,
    })
    await prisma.course.createMany({
        data: course,
    });
    console.log("Undo the comment");
};

Seed()
  .catch((e) => {
    console.error("Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

// run node prisma/seed/seed.js